---
- name: Push files to GitHub repository
  hosts: controller  # Assuming you run this playbook locally

  tasks:
    - name: Add all files to the staging area
      ansible.builtin.command: git add .
      args:
        chdir: /home/candi/Demo-ansible
      become: true

    - name: Commit changes
      ansible.builtin.command: git commit -m "Add new file"
      args:
        chdir: /home/candi/Demo-ansible
      become: true

    - name: Push to GitHub (main branch)
      ansible.builtin.command: git push origin main
      args:
        chdir: /home/candi/Demo-ansible
      become: true

