---
- name: Push files to GitHub repository
  hosts: localhost  # Assuming you run this playbook locally

  vars_files:
    - github_credentials.yml

  tasks:
    - name: Set Git credentials for HTTPS authentication
      ansible.builtin.set_fact:
        git_credentials: "{{ github_username }}:{{ github_password }}@github.com"

    - name: Change remote URL to HTTPS with credentials
      ansible.builtin.command: git remote set-url origin https://{{ git_credentials }}/candi2002/Demo-ansible.git
      args:
        chdir: /home/candi/Demo-ansible
      become: true

    - name: Add all files to the staging area
      ansible.builtin.command: git add .
      args:
        chdir: /home/candi/Demo-ansible
      become: true

    - name: Commit changes
      ansible.builtin.command: git commit -m "Add new file"
      args:
        chdir: /home/candi/Demo-ansible
      become: true

    - name: Push to GitHub (main branch)
      ansible.builtin.command: git push origin main
      args:
        chdir: /home/candi/Demo-ansible
      become: true
