---
- name: Install Snake game and copy to other hosts
  hosts: all
  become: true
  vars: 
    path_dest: "/opt/snake"
    path_game_local: "/home/candi/Demo-ansible/game/Cpp-Snake/main.cpp"

  tasks:
    - name: Install dependencies (gcc, g++)
      apt:
        name:
          - gcc
          - g++
        state: present
        update_cache: yes

    - name: Create directory for Snake game
      file:
        path: "{{ path_dest }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy game source code to hosts
      copy:
        src: "{{ path_game_local }}"
        dest: "{{ path_dest }}/main.cpp"
        owner: root
        group: root
        mode: '0644'
      delegate_to: localhost  # Copy từ controller tới hosts
      become: true

    - name: Verify that the main.cpp file exists on the remote hosts
      stat:
        path: "{{ path_dest }}/main.cpp"
      register: remote_file

    - name: Compile game
      command: g++ -o {{ path_dest }}/snake {{ path_dest }}/main.cpp
      args:
        chdir: "{{ path_dest }}"
      when: remote_file.stat.exists
